### ISSUE TITLE
Make background HTTP calls browser agnostic

### ISSUE THREAD

**Issue by davidsalvador** [co-inform/browser-plugin#9]
In line 242 of `src/js/browser-plugin.js` there is a reference to the object `chrome`. This object won't be available when running on a Firefox browser.

**Comment by aleixac** [comment]
Firefox browser, although it implements the more appropriate named "browser" namespace object, it also implements the "chrome" namespace object, and for the moment it is more appropriate for us and widely used, so while it is supported by both browsers I still recommend to use the "chrome" one.
